fix: error reports for missing job owners
Resolves the following error:
> Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [owner] query: select * from "jobs" where "owner" = ?
      at QueryCompiler_PG.toSQL (/home/alemayhu/src/github.com/2anki/2anki.net/node_modules/knex/lib/query/querycompiler.js:112:13)
      at QueryBuilder_PostgreSQL.toSQL (/home/alemayhu/src/github.com/2anki/2anki.net/node_modules/knex/lib/query/querybuilder.js:84:44)
      at ensureConnectionCallback (/home/alemayhu/src/github.com/2anki/2anki.net/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
      at Runner.ensureConnection (/home/alemayhu/src/github.com/2anki/2anki.net/node_modules/knex/lib/execution/runner.js:318:20)
      at Runner.run (/home/alemayhu/src/github.com/2anki/2anki.net/node_modules/knex/lib/execution/runner.js:30:19)

  Request path: /api/upload/jobs
  Method: GET
  Query: {}
  Body: undefined