github: use python 3.9
This should hopefully resolve the below error, but need to trigger the
action to be sure. Come on GitHub, there has to be a better way to test
actions than this...

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a98sqdfv/pystache/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a98sqdfv/pystache/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-a98sqdfv/pystache/pip-egg-info
         cwd: /tmp/pip-install-a98sqdfv/pystache/
    Complete output (3 lines):
    pystache: using: version '58.0.4' of <module 'setuptools' from '/home/runner/.local/lib/python3.8/site-packages/setuptools/__init__.py'>
    Warning: 'classifiers' should be a list, got type 'tuple'
    error in pystache setup command: use_2to3 is invalid.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.